language: node_js
node_js:
- '6'
deploy:
  provider: heroku
  api_key:
    secure: JXUpkOqWmwCYlO4ED9gJ4Gao2SW48Xi3kxWuaypCSc9luplf2GwTiHNsE1/emamDkPw1iGawYlfoqLNOEigO+3qyHO6QEqmylR4G19EWnX/MoGWmaRiZicMQQiFXcqLA2Zmik83ZwI44iRJuwUJkwUV8czx8wzUA/pWxBQUFiVg0zNkFmjUUXtwTPWPWnZNAvgN91nAYyx2aZGjoF/Kz81py52Qc237ikDBFk32qGe068Jg0j4U6ONzR8bYHqhuz9AoPEqbiMqXSP9R3hxupct9L4Kf3r3Apc9kUN7jo0LEg0jRwSTyI8K+RNxFDDmbDK/gW7YbSDe+S0nRn1rGRh3joV5DAOOvwnSciTZrr5fnctvBd2N6O9FhjM6geQSU1589mZktBGr/8thHuVqrUO54RwRkxk3x50m6eqkWvga8gzeaDgqR28kS2w2sRkyMqTxMurSd7ZgKYZbNBbIn6sTumZ+5fa+I53kcDjIpN+WMn9dmQCfA+deoztSPDGC7vxnsxDbVlrrLZlzhCgZxwReGfrQLKZ3XuxMyNpJsPoitU8jqzYErdNhpztt5EoYfsouClK+t5gnn5XfUbCkm4EExhKysuFtItI7yN+U9nla/e09tzjkmvfaUsZ22hqTUyeYe2kenNVRTbrG9xfjgJ4mIhaLLt5q7AmzFZXAmu2EM=
  app: ingredientstoday
cache:
  yarn: true
#  directories:
#    - node_modules
